package workspace

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/hollowhemlock/desky/internal/fileio"
)

type registry struct {
	SchemaVersion int        `json:"schema_version"`
	Checkouts     []Checkout `json:"checkouts"`
}

type store struct {
	dir         string
	write       func(string, []byte, bool) error
	lockTimeout time.Duration
}

func newStore(dir string) store { return store{dir, fileio.Write, 2 * time.Second} }

func strictJSON(data []byte, dst any) error {
	d := json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(dst); err != nil {
		return fmt.Errorf("invalid JSON schema")
	}
	if err := d.Decode(new(any)); err != io.EOF {
		return fmt.Errorf("unexpected data after JSON document")
	}
	return nil
}

func validateCheckout(c Checkout) error {
	if !uuidPattern.MatchString(c.CheckoutID) || !uuidPattern.MatchString(c.WorkspaceID) || c.CheckoutID != strings.ToLower(c.CheckoutID) || c.WorkspaceID != strings.ToLower(c.WorkspaceID) {
		return fmt.Errorf("invalid checkout/workspace UUID")
	}
	if !filepath.IsAbs(c.RootPath) || !validName(c.Name) || (c.IdentitySource != "explicit" && c.IdentitySource != "directory") {
		return fmt.Errorf("invalid checkout metadata")
	}
	return nil
}

func (s store) read() (registry, error) {
	r := registry{SchemaVersion: 1, Checkouts: []Checkout{}}
	data, err := fileio.ReadRegular(filepath.Join(s.dir, "registry.json"))
	if os.IsNotExist(err) {
		return r, nil
	}
	if err != nil {
		return r, stateError(err)
	}
	r = registry{}
	if err := strictJSON(data, &r); err != nil {
		return r, stateError(err)
	}
	if r.SchemaVersion != 1 || r.Checkouts == nil {
		return r, stateError(fmt.Errorf("unsupported registry schema"))
	}
	ids := map[string]bool{}
	paths := map[string]bool{}
	// Keep FileInfo objects for this read: os.SameFile lazily caches native file
	// identities on Windows. Re-statting every pair makes a 1,000-entry picker
	// perform roughly a million filesystem reads.
	stats := make([]os.FileInfo, 0, len(r.Checkouts))
	for i, c := range r.Checkouts {
		if err := validateCheckout(c); err != nil {
			return r, stateError(err)
		}
		if ids[c.CheckoutID] {
			return r, stateError(fmt.Errorf("duplicate checkout ID"))
		}
		ids[c.CheckoutID] = true
		path := filepath.Clean(c.RootPath)
		if paths[path] {
			return r, stateError(fmt.Errorf("duplicate checkout path"))
		}
		paths[path] = true
		st, _ := os.Stat(c.RootPath)
		for _, prior := range stats[:i] {
			if st != nil && prior != nil && os.SameFile(prior, st) {
				return r, stateError(fmt.Errorf("duplicate checkout path"))
			}
		}
		stats = append(stats, st)
	}
	return r, nil
}

func sameDirectory(a, b string) bool {
	if filepath.Clean(a) == filepath.Clean(b) {
		return true
	}
	x, err := os.Stat(a)
	if err != nil {
		return false
	}
	y, err := os.Stat(b)
	return err == nil && os.SameFile(x, y)
}

func (s store) save(r registry) error {
	path := filepath.Join(s.dir, "registry.json")
	old, err := fileio.ReadRegular(path)
	if err != nil && !os.IsNotExist(err) {
		return stateError(err)
	}
	if err == nil {
		if err := s.write(path+".bak", old, true); err != nil {
			return stateError(err)
		}
	}
	data, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return stateError(err)
	}
	if err := s.write(path, append(data, '\n'), true); err != nil {
		return stateError(err)
	}
	return nil
}

// A journal spans the two filesystems used by init. Recovery only publishes the
// exact prepared config; it never adopts or overwrites another existing config.
type pendingInit struct {
	SchemaVersion int      `json:"schema_version"`
	Checkout      Checkout `json:"checkout"`
	Config        []byte   `json:"config"`
}

func (s store) recover(r *registry) (*Checkout, error) {
	p := filepath.Join(s.dir, "pending-init.json")
	data, err := fileio.ReadRegular(p)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, stateError(err)
	}
	var pending pendingInit
	if err := strictJSON(data, &pending); err != nil {
		return nil, stateError(err)
	}
	if pending.SchemaVersion != 1 || validateCheckout(pending.Checkout) != nil {
		return nil, stateError(fmt.Errorf("invalid pending init schema"))
	}
	c := pending.Checkout
	// Validate journal intent before writing to a checkout. Config is generated by
	// init, so matching its canonical bytes also rejects arbitrary injected recipes.
	expected, err := initialConfig(c.WorkspaceID, c.Name)
	if err != nil || !bytes.Equal(expected, pending.Config) || c.IdentitySource != "explicit" {
		return nil, stateError(fmt.Errorf("invalid pending init configuration"))
	}
	root, err := canonicalDirectory(c.RootPath)
	if err != nil || root != c.RootPath {
		return nil, stateError(fmt.Errorf("pending init root moved or is unavailable"))
	}
	path := filepath.Join(root, "workspace.toml")
	existing, err := fileio.ReadRegular(path)
	if os.IsNotExist(err) {
		if err = s.write(path, pending.Config, false); err != nil {
			return nil, stateError(fmt.Errorf("init is pending; retry init after resolving config publication: %w", err))
		}
	} else if err != nil || !bytes.Equal(existing, pending.Config) {
		return nil, stateError(fmt.Errorf("pending init conflicts with workspace.toml; preserve both files and restore the prepared configuration before retrying"))
	}
	index := checkoutIndex(*r, root)
	if index >= 0 {
		old := r.Checkouts[index]
		if old.CheckoutID != c.CheckoutID || old.WorkspaceID != c.WorkspaceID {
			return nil, stateError(fmt.Errorf("pending init conflicts with registry identity"))
		}
		r.Checkouts[index] = c
	} else {
		r.Checkouts = append(r.Checkouts, c)
	}
	if err := s.save(*r); err != nil {
		return nil, err
	}
	if err := fileio.RemovePublished(p); err != nil {
		return nil, stateError(err)
	}
	return &c, nil
}

func checkoutIndex(r registry, root string) int {
	for i, c := range r.Checkouts {
		if sameDirectory(c.RootPath, root) {
			return i
		}
	}
	return -1
}
